config/routes.rb
Liquorlicensehq::Application.routes.draw do
  
  resources :criterias

  resources :license_types

  resources :user_details

  resources :liquor_license_auctions

  get "home/index"
  get "users/login"
  get "users/confirm"
  get "liquor_licenses/get_my_auction"
  get "users/import_data"
  get "liquor_licenses/get_cities"
  get "liquor_licenses/delete_record"
  get "liquor_licenses/accept"
  get "users/logout"
  get "users/check_criteria"
  get "criterias/delete_record"
  get "users/private"
  get "users/contact_us"
  get "home/search"
  get "users/sendmail_criteria_activity"
  get "users/forgot"
  get "users/sendmail"
  get "liquor_licenses/paypal_request"
  get "liquor_licenses/get_craigslist"
  get "liquor_licenses/get_for_sale"
  get "liquor_licenses/get_for_buy"
  get "liquor_licenses/get_for_both"
  get "users/check_bid"
  get "users/sendmail_bid_activity"
  resources :users
  resources :liquor_licenses

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
require 'yaml'
require 'geoinfo'
require 'nokogiri'
require 'open-uri'
class User < ActiveRecord::Base

  validates :username , :kind ,:presence => true
  validates_uniqueness_of :email
  validates_uniqueness_of :username
  validates_length_of :username, :within => 5..50
  validates_length_of :password, :within => 5..50
  validates_confirmation_of :password 
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "must be valid"
  before_save :hash_password
  def hash_password
    if password_changed?
      self.password = Digest::SHA1.hexdigest(password)
    end
  end
  has_many :liquor_licenses ,:dependent => :destroy
  has_one :user_detail, :dependent=> :destroy
  has_many :criterias, :dependent => :destroy
  has_many :criteria_activities, :dependent => :destroy
  has_many :liquor_license_auctions
  has_many :bid_activities
  def User.check_criteria
    @users = User.find(:all)
    @users.each do |user|
      result = []
      user.criterias.each do |criteria|

        if user.kind == "Selling"
          conditions = {}
          conditions[:today] = Date.today()
          conditions[:purpose] = 'Buy'
          conditions[:user_id] = user.id
          conditions[:state_id] = criteria.state_id
          conditions[:city_id] = criteria.city_id
          conditions[:license_type_id] = criteria.license_type_id
          result_selling = LiquorLicense.where("(expiration_date >= :today OR expiration_date IS NULL) AND purpose = :purpose AND (user_id != :user_id or user_id IS NULL) AND state_id = :state_id AND city_id = :city_id AND license_type_id = :license_type_id" , conditions)
          if result_selling
            result = result + result_selling
          end
        end
        if user.kind == "Buying"
          conditions = {}
          conditions[:today] = Date.today()
          conditions[:purpose] = 'Sell'
          conditions[:user_id] = user.id
          conditions[:state_id] = criteria.state_id
          conditions[:city_id] = criteria.city_id
          conditions[:license_type_id] = criteria.license_type_id
          result_buying = LiquorLicense.where("(expiration_date >= :today OR expiration_date IS NULL) AND purpose = :purpose AND (user_id != :user_id or user_id IS NULL) AND state_id = :state_id AND city_id = :city_id AND license_type_id = :license_type_id" , conditions)
          if result_buying
            result = result + result_buying
          end
        end
        if user.kind == "Both"
          conditions = {}
          conditions[:today] = Date.today()
          conditions[:user_id] = user.id
          conditions[:state_id] = criteria.state_id
          conditions[:city_id] = criteria.city_id
          conditions[:license_type_id] = criteria.license_type_id
          result_both = LiquorLicense.where("(expiration_date >= :today OR expiration_date IS NULL) AND (user_id != :user_id or user_id IS NULL) AND state_id = :state_id AND city_id = :city_id AND license_type_id = :license_type_id" , conditions)
          if result_both
            result = result + result_both
          end
        end
        if result 
          result.each do |liquor_license_each|
            criteria_activity = CriteriaActivity.where(:liquor_license_id => liquor_license_each.id, :user_id => user.id).first
            if criteria_activity == nil
              criteria_activity = CriteriaActivity.new(:liquor_license_id => liquor_license_each.id, :user_id => user.id, :expiration_date => liquor_license_each.expiration_date, :status => false)
              criteria_activity.save()
            end
          end

        end
      end
    end
    
  end
  def User.sendmail_criteria_activity
    @users = User.find(:all)
    subject = 'Your Criteria about Liquor License'
    @users.each do |user|
      check = false
      user.criteria_activities.each do |criteria_activity|
        if criteria_activity.status == false
          check = true
        end
      end
      if check == true
        UserMailer.criteria_activity( subject, user).deliver
      end
    end

  end
  def User.check_bid
    @users = User.find(:all)
    @users.each do |user|
      if user.kind == 'Buying' or user.kind == 'Both'
        auctions = LiquorLicenseAuction.where(:bidder_id => user.id)
        auctions.each do |auction|
          conditions = {}
          if LiquorLicense.find_by_id(auction.liquor_license_id)
            if  LiquorLicense.find_by_id(auction.liquor_license_id).purpose == 'Sell'

              conditions[:liquor_license_id] = auction.liquor_license_id
              liquor_license_auction = LiquorLicenseAuction.where(" liquor_license_id = :liquor_license_id" ,conditions).order("price desc").first
              if liquor_license_auction and liquor_license_auction.bidder_id != user.id
                conditions = {}
                conditions[:user_id] = user.id
                conditions[:liquor_license_auction_id] = liquor_license_auction.id
                bid_activity = BidActivity.where("user_id = :user_id AND liquor_license_auction_id = :liquor_license_auction_id" ,conditions).first
                if bid_activity == nil
                  bid_activity = BidActivity.new(:user_id => user.id, :liquor_license_auction_id => liquor_license_auction.id, :status => false, :expiration_date => liquor_license_auction.liquor_license.expiration_date )
                  bid_activity.save()
                end
              end
            end
          end
        end
      end
    end
  end
  def User.sendmail_bid_activity
    subject = 'Bid Higher'
    bid_activities = BidActivity.find(:all)
    bid_activities.each do |bid_activity|
      if bid_activity.status == false
        UserMailer.bid_activity( subject, bid_activity).deliver
      end
    end

  end
  def User.get_craigslist
    # Get a Nokogiri::HTML:Document for the page we’re interested in...
    
      
    doc = Nokogiri::HTML(open('http://www.craigslist.org/about/sites'))
    doc.xpath('//li/a').each do |link|
      @state_id = nil
      @city_id = nil
      location = []
      place = link.text
      location << place.strip 
      if location[0].include? '-' 
        location = location[0].split(/-/)
      end
      if location[0].include? '/'
        location = location[0].split(/\//)
      end
      if location[0]
        conditions = {}
        conditions[:name] =  location[0].upcase  
        city_result = GeoinfoCity.where("name = :name", conditions).find(:all, :order => "population_2000 desc").first
        
        if city_result 
          state_result = GeoinfoState.find_by_id(city_result.state_id)
          if state_result
            @state_id = city_result.state_id
          end
          @city_id = city_result.id
        else 
          check_location = nil
          if location[0].upcase.split(" ").length >= 2
            check_location = location[0].sub("county", '').sub("bay", '').sub("area", '')
            conditions[:name] =  check_location.upcase.strip   
            city_result = GeoinfoCity.where("name = :name", conditions).find(:all, :order => "population_2000 desc").first
            if city_result 
              state_result = GeoinfoState.find_by_id(city_result.state_id)
              if state_result
              
                @state_id = city_result.state_id
              end
              @city_id = city_result.id
         
            else 
              if location[0].upcase.split(" ").length > 2
                check_location = location[0].sub("city", '')
                conditions[:name] = check_location.upcase.strip
                city_result = GeoinfoCity.where("name = :name", conditions).find(:all, :order => "population_2000 desc").first
                if city_result 
                  state_result = GeoinfoState.find_by_id(city_result.state_id)
                  if state_result
                    @state_id = city_result.state_id
                  end
                  @city_id = city_result.id
                end
              end
            end 
          end

          

        end 
        begin
          doc_detail = Nokogiri::HTML(open(link['href'] + '/search/bfs?query=liquor+license&catAbb=sss&srchType=A&minAsk=&maxAsk='))
          if doc_detail
            check = true
            doc_detail.xpath('//h4[@class="ban"]').each do |check_detail| 
              if check_detail.text == "Zero LOCAL results found. Here are some from NEARBY areas..."
                check = false
              end
            end
            if check 
              doc_detail.xpath('//p[@class="row"]').each do |link_detail|

                break if link_detail.next_sibling.text == "Few LOCAL results found. Here are some from NEARBY areas..." 
                break if link_detail.next_sibling.text == "Zero LOCAL results found. Here are some from NEARBY areas..." 
                index = link_detail.content.index('-') - 1
                title = nil
                url = nil
                email = nil

                license_type_id = nil

                price = 0
                created_at = Date.parse(link_detail.content[10..index] + Date.today().year().to_s )
                #logger.info Date.strptime(link.content[10..index] + Date.today().year().to_s ,"%b %d %yyyy")
                if link_detail.at('a')
                  if link_detail.at('a').text != nil and link_detail.at('a').text != ''
                    if link_detail.at('a').text.index('-')
                      index = link_detail.at('a').text.index('-') - 1
                      title = link_detail.at('a').text[0, index]
                    end
                  end
                  url = link_detail.at('a')['href']
                  logger.info 'aa'
                  logger.info url
                  if url 
                    begin
                      doc_detail_more = Nokogiri::HTML(open(url))
                      if doc_detail_more
                        doc_detail_more.xpath('//a').each do |link_detail_more|

app/controllers/users_controller.rb
require 'digest/sha1'
require 'recaptcha'
require 'yaml'
require 'geoinfo'
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.username != 'admin'
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    logger.info 'huyen anh'
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end
  def confirm
    
    @user = User.new(params[:user])
    unless @user.valid?
      render :action => :new     
    else 
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.id != @user.id
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        format.html { redirect_to(:controller => 'users', :action =>"private", :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    logger.info 'ffffff'
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  def authenticate
    #User.new(params[:userform]) will create a new object of User, retrieve values from the form and store it variable @user.
    @user = User.new(params[:userform])
    #find records with username,password
    valid_user = User.find(:first, :conditions => ["username = ? and password = ?", @user.username, Digest::SHA1.hexdigest(@user.password)])

    #if statement checks whether valid_user exists or not
    if valid_user
      #creates a session with username
      session[:user_id]=valid_user.username
      #redirects the user to our private page.
      redirect_to '/'
    else
      flash[:notice] = "Invalid User/Password"
      redirect_to :action=> 'login'
    end
  end

  def login
  end

  def forgot
  end

  def private

    if !session[:user_id]
      redirect_to :action=> 'login'
    end
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
  end

  def logout
    if session[:user_id]
      reset_session
      redirect_to '/'
    end
  end

  def sendmail
    recipient = params[:mailform][:email]
    subject = 'Get your password'
    user = User.find(:first, :conditions => ["email = ? ", recipient])
    chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ23456789'
    password = ''
    6.times { |i| password << chars[rand(chars.length)] }

    if user
      user.password = password
      UserMailer.forgot(recipient, subject, user).deliver
      user.update_attributes(:password => password)
    else
      render :text => recipient + " doesn't exist in the system"
      return
    end
    return if request.xhr?
    render :text => 'Message sent successfully'
  end 
  def contact_us
    



  end
  def send_contact_us

    respond_to do |format|
      if verify_recaptcha( :message => "Oh! It's error with reCAPTCHA!")
        recipient = 'nhut2020@yahoo.com'
        subject = params[:contact_us][:subject]
        user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
        message =  params[:contact_us][:message]
        UserMailer.contact_us(recipient, subject, user, message).deliver
        format.html { redirect_to(:controller => 'users', :action =>"private") }
      else
        format.html { redirect_to(:controller => 'users', :action =>"contact_us", :notice => { :error => "Oh! It's error with reCAPTCHA!" ,:subject => params[:contact_us][:subject] , :message => params[:contact_us][:message]})}
      end
    end
  end
  def import_data
    states = File.open( "public/geoinfo_states.yml" )
    YAML::load_documents( states ) { |doc|
      state = GeoinfoState.new
      state.name = doc['name']
      state.abbr = doc['abbr']
      state.country = doc['country']
      state.kind = doc['type']
      state.id = doc['id']
      state.save()
    }

    cities = File.open( "public/geoinfo_cities.yml" )
    YAML::load_documents( cities ) { |doc|
      city = GeoinfoCity.new
      city.name = doc['name']
      city.population_2000 = doc['population_2000']
      city.state_id = doc['state_id']
      city.gnis_id = doc['gnis_id']
      city.latitude = doc['latitude']
      city.longitude = doc['longitude']
      city.save()
    }

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
<div class="field">
    <%= f.label :type %><br />
    <%= f.radio_button "kind", "Selling" %>Selling
    <%= f.radio_button "kind", "Buying" %>Buying
    <%= f.radio_button "kind", "Both" %>Both
  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h1>Thank you for registering to LiquorLicenseHQ.com </h1>
<%= form_for(@user, :url => {:action => "create"}) do |f| %>
<%= link_to 'Home', home_index_path %>
<p/>
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= html_escape(@user.email) %>
</p>

<p>
  <b>Username:</b>
  <%= html_escape(@user.username) %>
</p>

<p>
  <b>Type:</b>
  <%= @user.kind %>
</p>
<%= f.hidden_field :username , :value =>  @user.username %>
<%= f.hidden_field :email , :value =>  @user.email %>
<%= f.hidden_field :password , :value =>  @user.password %>
<%= f.hidden_field :kind , :value =>  @user.kind %>
 <div class="actions">
    <%= f.submit 'Confirm User' %>
  </div>
<% end %>
<%= link_to 'Back', new_user_path %>

app/views/users/contact_us.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<% if params[:notice] %>
  <% if params[:notice][:error] %>
  <div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
  
    <%= params[:notice][:error] %>
  </div>
<% end %>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'send_contact_us' %>

<p>
  <b>Subject:</b> <br/>
  <%= text_field("contact_us", "subject",:size=>"53" , :maxlength => '255', :value => params[:notice] ? params[:notice][:subject] : '') %>
</p>

<p>
  <b>Message:</b>
  <b</b><br/>
  <%= text_area("contact_us" ,"message", :size => "40x10", :value => params[:notice] ? params[:notice][:message] : '') %>
</p>
<script type="text/javascript">
	
  function checkValidate() {

    if ($("#contact_us_subject").val() == null || $("#contact_us_subject").val() == '') {
      alert ("Please type in Subject");
      return false; 
    }
    if ($("#contact_us_message").val() == null || $("#contact_us_message").val() == '') {
      alert ("Please type in Message");
      return false; 
    }
                        
    return true;

  }
</script>
<%= recaptcha_tags %>
<input type="submit" value=" Send " onclick=" return checkValidate();"/>
<br/>
<%= link_to 'Back', url_for(:back) %>

app/views/users/edit.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Editing User</h1>

<%= render 'form' %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/forgot.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<% if flash[:notice] %>
<div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
<%= flash[:notice] %>
</div>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'sendmail' %>
Send Mail to get your password:
<br/>
<%= text_field("mailform", "email",:size=>"20" ) %>

<input type="submit" value=" Send " />

app/views/users/index.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Username</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= html_escape(user.email) %></td>
    <td><%= html_escape(user.username) %></td>
    <td><%= user.kind %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<% if flash[:notice] %>
<div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
<%= flash[:notice] %>
</div>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'authenticate' %>
User name:
<br/>
<%= text_field("userform", "username",:size=>"20" ) %>
<br/>
Password:
<br/>
<%= password_field("userform", "password",:size=>"20" )
%>
<br/>
<%= link_to 'Forgot password' ,:controller => "users", :action => "forgot" %>
<br/>
<input type="submit" value=" LOGIN " />

app/views/users/new.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Sign Up</h1>

<%= form_for(@user, :url => {:action => "confirm"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
<div class="field">
    <%= f.label :type %><br />
    <%= f.radio_button "kind", "Selling" %>Selling
    <%= f.radio_button "kind", "Buying" %>Buying
    <%= f.radio_button "kind", "Both" %>Both
  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', users_path %>

app/views/users/private.html.erb
<!--#displays hello (username)-->
hello <strong><%=session[:user_id]%></strong>.
<%= image_tag @valid_user.user_detail ? (@valid_user.user_detail.avatar ? @valid_user.user_detail.avatar : 'logo.jpg')  : 'logo.jpg', :size => "60x60" %>
<!--#creates logout link, when the link is clicked, the controller is User and the method executed will be logout.-->
<%= link_to "logout",:controller => "users", :action => "logout" %> | <%= link_to 'Setting User', edit_user_path(@valid_user) %>
| <%= link_to 'New Liquor license', new_liquor_license_path %> | 
<%if @valid_user.user_detail%>
  <%= link_to 'Account Detail', edit_user_detail_path(@valid_user.user_detail) %>
<% else %>
  <%= link_to 'Account Details', new_user_detail_path%>
<% end %>
|  <%= link_to 'Liquor Licenses from Craigslist', :controller => "liquor_licenses", :action => "get_craigslist"%>
| 
<% if @valid_user.kind =="Selling" %>
  <%= link_to 'Liquor Licenses for Seller', :controller => "liquor_licenses", :action => "get_for_sale"%>
<% end %>
<% if @valid_user.kind =="Buying" %>
  <%= link_to 'Liquor Licenses for Buyer', :controller => "liquor_licenses", :action => "get_for_buy"%>
<% end %>
<% if @valid_user.kind =="Both" %>
  <%= link_to 'Liquor Licenses', :controller => "liquor_licenses", :action => "get_for_both"%>
<% end %>
|
  <%= link_to 'My Auction', :controller => "liquor_licenses", :action => "get_my_auction"%>
|
<%= link_to 'My Liquor Licenses', liquor_licenses_path %>
|
<%if @valid_user.criteria %>
  <%= link_to 'My Criteria', edit_criteria_path(@valid_user.criteria) %>
<% else %>
  <%= link_to 'My Criteria', new_criteria_path%>
<% end %>

|
<%= link_to "Contact Us",:controller => "users", :action => "contact_us" %>

app/views/users/show.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= html_escape(@user.email) %>
</p>

<p>
  <b>Username:</b>
  <%= html_escape(@user.username) %>
</p>

<p>
  <b>Type:</b>
  <%= @user.kind %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>