config/routes.rb
Liquorlicensehq::Application.routes.draw do
  
  resources :criterias

  resources :license_types

  resources :user_details

  resources :liquor_license_auctions

  get "home/index"
  get "users/login"
  get "users/confirm"
  get "liquor_licenses/get_my_auction"
  get "users/import_data"
  get "liquor_licenses/get_cities"
  get "liquor_licenses/delete_record"
  get "liquor_licenses/accept"
  get "users/logout"
  get "users/check_criteria"
  get "criterias/delete_record"
  get "users/private"
  get "users/contact_us"
  get "home/search"
  get "users/sendmail_criteria_activity"
  get "users/forgot"
  get "users/sendmail"
  get "liquor_licenses/paypal_request"
  get "liquor_licenses/get_craigslist"
  get "liquor_licenses/get_for_sale"
  get "liquor_licenses/get_for_buy"
  get "liquor_licenses/get_for_both"
  get "users/check_bid"
  get "users/sendmail_bid_activity"
  resources :users
  resources :liquor_licenses

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/home_controller.rb
require 'geoinfo'
class HomeController < ApplicationController
  sortable_attributes :title  , :expiration_date, :price
  def index
    if session[:user_id]
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    end
    @states = GeoinfoState.find(:all, :order => 'name asc')
    conditions = {}

    
    conditions[:today] = Date.today()
    conditions[:before] = Date.today() - 60
    result = LiquorLicense.where("(expiration_date >= :today OR expiration_date IS NULL) AND  created_at >= :before", conditions).find :all, :order => sort_order, :limit => 1000
    @liquor_licenses = result.paginate(:page => params[:page] ,:per_page => 20)
  end
  def search
    query_string = ""
    conditions = {}
    if params[:liquor_license] and params[:liquor_license][:state_id] != nil and params[:liquor_license][:state_id] != ''
      @state_first = GeoinfoState.find(params[:liquor_license][:state_id])
    end
    logger.info params
    if params[:search] and params[:search][:id]
      @state_first = GeoinfoState.find(params[:search][:id])
    end
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '2').find :all, :order => "name asc"
    @selected_city = nil
    if params[:liquor_license] and params[:liquor_license][:city_id] 
      @selected_city = GeoinfoCity.where(:id => params[:liquor_license][:city_id]).first
    end
     if params[:search] and params[:search][:id]
      logger.info 'aaaaaaaaaaaasaa'
      query_string = query_string + " AND state_id = :state_id"  
      conditions[:state_id] = params[:search][:id]
    end
    if params[:liquor_license]
      if params[:liquor_license][:title] != nil and params[:liquor_license][:title] != ''
         logger.info 'aaaaaaabbbbbbbbbbbaaaaaaa'
        query_string = query_string + " AND UPPER(title) LIKE :title"  
        conditions[:title] = "%" + params[:liquor_license][:title].strip.upcase + "%"
      end
      if params[:liquor_license][:state_id] != nil and params[:liquor_license][:state_id] != ''
        query_string = query_string + " AND state_id = :state_id"  
        conditions[:state_id] = params[:liquor_license][:state_id]
      end
      if params[:liquor_license][:city_id] != nil and params[:liquor_license][:city_id] != ''
         logger.info 'aaaaaaaaaaaccccccccccaaa'
        query_string = query_string + " AND city_id = :city_id"  
        conditions[:city_id] = params[:liquor_license][:city_id]
      end
      if params[:liquor_license][:price_min] != nil and params[:liquor_license][:price_min] != ''
        query_string = query_string + " AND price >= :price_min"  
        conditions[:price_min] = params[:liquor_license][:price_min].to_i
      end
      if params[:liquor_license][:price_max] != nil and params[:liquor_license][:price_max] != ''
        query_string = query_string + " AND price <= :price_max"  
        conditions[:price_max] = params[:liquor_license][:price_max].to_i
      end
      if params[:liquor_license][:license_type_id] != nil and params[:liquor_license][:license_type_id] != ''
 
        query_string = query_string + " AND license_type_id = :license_type_id"  
        conditions[:license_type_id] = params[:liquor_license][:license_type_id]
      end
    end
    conditions[:today] = Date.today()
    logger.info conditions
    result = LiquorLicense.where("(expiration_date >= :today OR expiration_date IS NULL) " + query_string , conditions).find :all, :order => sort_order
    logger.info 'buon boi'
    @liquor_licenses = result.paginate(:page => params[:page] ,:per_page => 20)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Liquor License HQ</h1>
<% if session[:user_id] == nil %>
  <%= link_to "Login",:controller => "users", :action => "login" %>
  |
  <%= link_to "Sign Up",:controller => "users", :action => "new" %>
<% else %>
  <!--#displays hello (username)-->
  hello <strong><%=session[:user_id]%></strong>.
  <%= image_tag @valid_user.user_detail ? (@valid_user.user_detail.avatar ? @valid_user.user_detail.avatar : 'logo.jpg')  : 'logo.jpg', :size => "60x60" %>
  <!--#creates logout link, when the link is clicked, the controller is User and the method executed will be logout.-->
  <%= link_to "logout",:controller => "users", :action => "logout" %> | <%= link_to 'Setting User', edit_user_path(@valid_user) %>
  | <%= link_to 'New Liquor license', new_liquor_license_path %> | 
  <%if @valid_user.user_detail%>
    <%= link_to 'Account Detail', edit_user_detail_path(@valid_user.user_detail) %>
  <% else %>
    <%= link_to 'Account Details', new_user_detail_path%>
  <% end %>
  | 
  <% if @valid_user.kind =="Selling" %>
    <%= link_to 'Liquor Licenses for Seller', :controller => "liquor_licenses", :action => "get_for_sale"%>
  <% end %>
  <% if @valid_user.kind =="Buying" %>
    <%= link_to 'Liquor Licenses for Buyer', :controller => "liquor_licenses", :action => "get_for_buy"%>
  <% end %>
  <% if @valid_user.kind =="Both" %>
    <%= link_to 'Liquor Licenses', :controller => "liquor_licenses", :action => "get_for_both"%>
  <% end %>
  |
  <%= link_to 'My Liquor Licenses', liquor_licenses_path %>
  |

  <%= link_to 'My Auction', :controller => "liquor_licenses", :action => "get_my_auction"%>
  |
  <%if @valid_user.criterias %>
    <%= link_to 'My Criteria', criterias_path %>
  
  <% else %>
    <%= link_to 'New Criteria', new_criteria_path%>
  <% end %>

|
<%= link_to "Contact Us",:controller => "users", :action => "contact_us" %>

<% end %>


<%= form_for :search, :url => { :action => "search" } do |f| %>

  State <%= f.select( :id , GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] })   %>
  <%= f.submit 'Search' %>
<% end %>
<h1>Listing New Liquor Licenses</h1>

<table>
  <tr>
    <%= sortable_table_header :name => "Title",  :sort => "title" %>
    <th>State</th>
    <th>City</th>
    <th>License Type</th>
    <%= sortable_table_header :name => "Price",   :sort => "price" %>

    <%= sortable_table_header :name => "Expiration Date", :sort => "expiration_date" %>

  </tr>

  <% @liquor_licenses.each do |liquor_license| %>
    <tr>
      <td><%= html_escape(liquor_license.title) %></td>
      <td><%= liquor_license.state_id ? GeoinfoState.find(liquor_license.state_id).name : '' %></td>
      <td><%= liquor_license.city_id ? ( GeoinfoCity.find(liquor_license.city_id) ? GeoinfoCity.find(liquor_license.city_id).name : '') : '' %></td>
      <td><%= liquor_license.license_type ? liquor_license.license_type.license_code + '-' + liquor_license.license_type.description : ''%></td> 
      <td> <%=  liquor_license.price != 0 ? '$':'' %> <%= liquor_license.price != 0 ? liquor_license.price  : '' %></td>
      <td><%= liquor_license.expiration_date %></td>

    </tr>
  <% end %>
</table>
<%= will_paginate @liquor_licenses %>
<br/>
<table>
  <tr><th valign="top">
<a href="http://twitter.com/share" class="twitter-share-button" style="width: 110px; height: 20px;" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</th>
    <th valign="top">
<a href="http://www.google.com/buzz/post"
    class="google-buzz-button"
    title="Google Buzz"
    data-url='<%= request.env["HTTP_HOST"] %>'
    data-locale="en"
    data-button-style="small-count"></a>
    <script type="text/javascript" src="http://www.google.com/buzz/api/button.js"></script>
 </th>
  <th valign="top">
<a name="fb_share" type="button_count" href="http://www.facebook.com/sharer.php">Share</a>

<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>

</th></tr>
</table>

app/views/home/search.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<%= form_for :liquor_license, :html => { :method => :get} do |f| %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $("select#liquor_license_state_id").change(function(){
        $.getJSON("/liquor_licenses/get_cities",{id: $(this).val(), ajax: 'true'}, function(j){
          var options = '';
          options +='<option value=""></option>';
          for (var i = 0; i < j.length; i++) {
       
            options += '<option value="' + j[i]['geoinfo_city']['id'] + '">' + j[i]['geoinfo_city']['name'] + '</option>';
          }
          $("select#liquor_license_city_id").html(options);

        })
      })
    })
  </script>
  <%= f.label :title %>
  <%= f.text_field :title, :value => params[:liquor_license] ? params[:liquor_license][:title] : '' %>
  <%= f.label :state %>
  <%= f.select(:state_id, GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] }, :selected  => @state_first ? @state_first.id : '', :include_blank => true) %> 
  <%= f.label :city %>
  <%= f.select(:city_id, @cities_first ? @cities_first.collect {|c| [ c.name, c.id ]} : '', :selected => @selected_city ? @selected_city.id : '' , :include_blank => true) %> 
    <%= f.label :license_type %>
   <%= f.select(:license_type_id, LicenseType.find(:all, :order => 'license_code asc').collect {|c| [c.license_code + '-' + c.description, c.id ] },  :selected  => params[:liquor_license] ? params[:liquor_license][:license_type_id] : '', :include_blank => true) %> 
 <br/>
  <%= f.label :price %>
  <%= f.text_field :price_min ,  :value => params[:liquor_license] ? params[:liquor_license][:price_min] : ''%> 
  <%= f.text_field :price_max ,  :value => params[:liquor_license] ? params[:liquor_license][:price_max] : ''%> 
  <h1>Listing Liquor Licenses</h1>

  <table>
    <tr>
      <%= sortable_table_header :name => "Title",  :sort => "title" %>
   <th>State</th>
 <th>City</th>
 <th>License Type</th>
      <%= sortable_table_header :name => "Price",   :sort => "price" %>

      <%= sortable_table_header :name => "Expiration Date", :sort => "expiration_date" %>
    </tr>

    <% @liquor_licenses.each do |liquor_license| %>
      <tr>
        <td><%= html_escape(liquor_license.title) %></td>
         <td><%= liquor_license.state_id ? GeoinfoState.find(liquor_license.state_id).name : '' %></td>
        <td><%= liquor_license.city_id ? GeoinfoCity.find(liquor_license.city_id).name : '' %></td>
        <td><%= liquor_license.license_type ? liquor_license.license_type.license_code + '-' + liquor_license.license_type.description : ''%></td>   
        <td><%=  liquor_license.price != 0 ? '$':'' %><%= liquor_license.price != 0 ? liquor_license.price  : '' %> </td>

        <td><%= liquor_license.expiration_date %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @liquor_licenses %>
  <br />
  <%= submit_tag("Search") %>
<% end %>
 <br/>
<table>
  <tr><th valign="top">
<a href="http://twitter.com/share" class="twitter-share-button" style="width: 110px; height: 20px;" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</th>
    <th valign="top">
<a href="http://www.google.com/buzz/post"
    class="google-buzz-button"
    title="Google Buzz"
    data-url='<%= request.env["HTTP_HOST"] %>'
    data-locale="en"
    data-button-style="small-count"></a>
    <script type="text/javascript" src="http://www.google.com/buzz/api/button.js"></script>
 </th>
  <th valign="top">
<a name="fb_share" type="button_count" href="http://www.facebook.com/sharer.php">Share</a>

<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>

</th></tr>
</table>