config/routes.rb
Liquorlicensehq::Application.routes.draw do
  
  resources :criterias

  resources :license_types

  resources :user_details

  resources :liquor_license_auctions

  get "home/index"
  get "users/login"
  get "users/confirm"
  get "liquor_licenses/get_my_auction"
  get "users/import_data"
  get "liquor_licenses/get_cities"
  get "liquor_licenses/delete_record"
  get "liquor_licenses/accept"
  get "users/logout"
  get "users/check_criteria"
  get "criterias/delete_record"
  get "users/private"
  get "users/contact_us"
  get "home/search"
  get "users/sendmail_criteria_activity"
  get "users/forgot"
  get "users/sendmail"
  get "liquor_licenses/paypal_request"
  get "liquor_licenses/get_craigslist"
  get "liquor_licenses/get_for_sale"
  get "liquor_licenses/get_for_buy"
  get "liquor_licenses/get_for_both"
  get "users/check_bid"
  get "users/sendmail_bid_activity"
  resources :users
  resources :liquor_licenses

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/liquor_licenses_controller.rb
require 'geoinfo'
require 'nokogiri'
require 'open-uri'
require "sortable_table"
class LiquorLicensesController < ApplicationController
  # GET /liquor_licenses
  # GET /liquor_licenses.xml
  sortable_attributes :title , :expiration_date, :price
  def index
    result = LiquorLicense.joins(:user).where("users.username = :username", {:username => session[:user_id]})
    logger.info session[:user_id]
    @liquor_licenses = result.paginate(:page => params[:page] ,:per_page => 1)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @liquor_licenses }
    end
  end
  # GET /liquor_licenses/1
  # GET /liquor_licenses/1.xml
  def view
    @liquor_license = LiquorLicense.find(params[:id])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user == nil
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    @liquor_license_auction =LiquorLicenseAuction.where(:liquor_license_id => params[:id], :bidder_id =>  @valid_user.id).first
    if params[:auction] and params[:auction][:bid] != '' and params[:auction][:bid].to_f > 0
      if  @liquor_license.user
        recipient = @liquor_license.user.email
        subject = "Bid Your Liquor License"
        message = params[:auction][:message]
        if recipient
          UserMailer.bid(recipient, subject, @valid_user, message, @liquor_license, params[:auction][:bid]).deliver
        end
      end
      if @liquor_license_auction != nil
        
        @liquor_license_auction.price = params[:auction][:bid].to_f
        @liquor_license_auction.status = false
        @liquor_license_auction.save()
      else
        logger.info 'abc'
        @liquor_license_auction = LiquorLicenseAuction.new
        @liquor_license_auction.price = params[:auction][:bid].to_f
        @liquor_license_auction.liquor_license = @liquor_license
        @liquor_license_auction.status = false
        @liquor_license_auction.bidder = @valid_user
        @liquor_license_auction.user = @liquor_license.user
        @liquor_license_auction.save()
        
      end
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @liquor_license }
    end
  end
  # GET /liquor_licenses/1
  # GET /liquor_licenses/1.xml
  def show
    @liquor_license = LiquorLicense.find(params[:id])
    @liquor_license_auctions = LiquorLicenseAuction.where(:liquor_license_id  => params[:id]).find :all, :order => 'price desc'
    logger.info @liquor_license_auctions
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @liquor_license }
    end
  end

  # GET /liquor_licenses/new
  # GET /liquor_licenses/new.xml
  def new
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user == nil
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    @liquor_license = LiquorLicense.new
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    @cities_first = GeoinfoCity.where(:state_id => '2').find :all, :order => "name asc"
    @selected_city = nil
    logger.info @cities_first
    if @liquor_license.city_id
      @selected_city = GeoinfoCity.find(@liquor_license.city_id)

    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @liquor_license }
    end
  end

  # GET /liquor_licenses/1/edit
  def edit
    @liquor_license = LiquorLicense.find(params[:id])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.id != @liquor_license.user_id
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    @state_first = GeoinfoState.find(@liquor_license.state_id)
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '2').find :all, :order => "name asc"
    @selected_city = nil
    if @liquor_license.city_id
      @selected_city = GeoinfoCity.find(@liquor_license.city_id)

    end

  end

  # POST /liquor_licenses
  # POST /liquor_licenses.xml
  def create
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    @liquor_license = @valid_user.liquor_licenses.create(params[:liquor_license])
    @state_first = GeoinfoState.find(:first, :order => 'name asc')
    if params[:liquor_license][:state_id]
      @state_first = GeoinfoState.find(params[:liquor_license][:state_id])
    end
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '2').find :all, :order => "name asc"
    @selected_city = nil
    if params[:liquor_license][:city_id] 
      @selected_city = GeoinfoCity.where(:id => params[:liquor_license][:city_id]).first

    end
    respond_to do |format|
      if @liquor_license.save
        format.html { redirect_to(@liquor_license, :notice => 'Liquor license was successfully created.') }
        format.xml  { render :xml => @liquor_license, :status => :created, :location => @liquor_license }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @liquor_license.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /liquor_licenses/1
  # PUT /liquor_licenses/1.xml
  def update
    @liquor_license = LiquorLicense.find(params[:id])

    respond_to do |format|
      if @liquor_license.update_attributes(params[:liquor_license])
        format.html { redirect_to(@liquor_license, :notice => 'Liquor license was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @liquor_license.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /liquor_licenses/1
  # DELETE /liquor_licenses/1.xml
  def delete_record
    @liquor_license = LiquorLicense.find(params[:id])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.id != @liquor_license.user_id
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    @liquor_license.destroy
    redirect_to(request.env["HTTP_REFERER"])

  end
  def paypal_request

    pay_request = PaypalAdaptive::Request.new
    @liquor_license = LiquorLicense.find(params[:id])  

    data = {
      "returnUrl" => "http://localhost:3000", 
      "requestEnvelope" => {"errorLanguage" => "en_US"},
      "currencyCode"=>"USD",  
      "receiverList"=>{"receiver"=>[{"email"=>"test1_1299037760_per@gmail.com", "amount"=>"10.00"}]},
      "cancelUrl"=>"http://localhost:3000",
      "actionType"=>"PAY",
      "ipnNotificationUrl"=>"http://localhost:3000"
    }

    pay_response = pay_request.pay(data)

    if pay_response.success?
      redirect_to pay_response.approve_paypal_payment_url
    else
      puts pay_response.errors.first['message']
      redirect_to failed_payment_url
    end

  end

  def get_for_sale
    query_string = ""
    conditions = {}
    @state_first = GeoinfoState.find(:first, :order => 'name asc')
   
    logger.info 'aaaa'
    if params[:liquor_license] and params[:liquor_license][:state_id] != nil and params[:liquor_license][:state_id] != ''
      @state_first = GeoinfoState.find(params[:liquor_license][:state_id])
    end
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '2').find :all, :order => "name asc"
    @selected_city = nil
    if params[:liquor_license] and params[:liquor_license][:city_id] 
      @selected_city = GeoinfoCity.where(:id => params[:liquor_license][:city_id]).first
    end
 
    if params[:liquor_license]
      if params[:liquor_license][:title] != nil and params[:liquor_license][:title] != ''
        logger.info 'aa'
        query_string = query_string + " AND UPPER(title) LIKE :title"  
        conditions[:title] = "%" + params[:liquor_license][:title].strip.upcase + "%"
      end
      if params[:liquor_license][:state_id] != nil and params[:liquor_license][:state_id] != ''
        query_string = query_string + " AND state_id = :state_id"  
        conditions[:state_id] = params[:liquor_license][:state_id]
      end
      if params[:liquor_license][:city_id] != nil and params[:liquor_license][:city_id] != ''
        query_string = query_string + " AND city_id = :city_id"  
        conditions[:city_id] = params[:liquor_license][:city_id]
      end
      if params[:liquor_license][:license_type_id] != nil and params[:liquor_license][:license_type_id] != ''
        logger.info 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

app/helpers/liquor_licenses_helper.rb
module LiquorLicensesHelper
end

app/views/liquor_licenses/edit.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Editing Liquor License</h1>

<%= render 'form' %>

<%= link_to 'Show', @liquor_license %> |
<%= link_to 'Back', liquor_licenses_path %>

app/views/liquor_licenses/get_craigslist.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Listing Liquor Licenses from Craigslist</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Price</th>
    <th>Created At</th>
    <th></th>
  </tr>

<% @liquor_licenses.each do |liquor_license| %>
  <tr>
    <td><%= link_to liquor_license.title, liquor_license.url %></td>
    <td><%= liquor_license.location %></td>
    <td><%= liquor_license.price != 0 ? liquor_license.price  : '' %> <%=  liquor_license.price != 0 ? '$':'' %></td>
    <td><%= liquor_license.created_at.strftime('%m-%d-%Y') %></td>
    <td><%= link_to 'Show', liquor_license %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Liquor license', new_liquor_license_path %>

app/views/liquor_licenses/get_for_both.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<%= form_for :liquor_license, :html => { :method => :get} do |f| %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $("select#liquor_license_state_id").change(function(){
        $.getJSON("/liquor_licenses/get_cities",{id: $(this).val(), ajax: 'true'}, function(j){
          var options = '';
          options +='<option value=""></option>';
          for (var i = 0; i < j.length; i++) {
       
            options += '<option value="' + j[i]['geoinfo_city']['id'] + '">' + j[i]['geoinfo_city']['name'] + '</option>';
          }
          $("select#liquor_license_city_id").html(options);

        })
      })
    })
  </script>
  <%= f.label :title %>
  <%= f.text_field :title, :value => params[:liquor_license] ? params[:liquor_license][:title] : '' %>
  <%= f.label :state %>
  <%= f.select(:state_id, GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] }, :selected  => params[:liquor_license] ? params[:liquor_license][:state_id] : '', :include_blank => true) %> 
  <%= f.label :city %>
  <%= f.select(:city_id, @cities_first ? @cities_first.collect {|c| [ c.name, c.id ]} : '', :selected => @selected_city ? @selected_city.id : '' , :include_blank => true) %> 
  <%= f.label :license_type %>
  <%= f.select(:license_type_id, LicenseType.find(:all, :order => 'license_code asc').collect {|c| [c.license_code + '-' + c.description, c.id ] },  :selected  => params[:liquor_license] ? params[:liquor_license][:license_type_id] : '', :include_blank => true) %> 
  <br/>
  <%= f.label :price %>
  <%= f.text_field :price_min ,  :value => params[:liquor_license] ? params[:liquor_license][:price_min] : ''%> 
  <%= f.text_field :price_max ,  :value => params[:liquor_license] ? params[:liquor_license][:price_max] : ''%> 
  <h1>Listing Liquor Licenses</h1>

  <table>
    <tr>
      <%= sortable_table_header :name => "Title",  :sort => "title" %>
      <th>State</th>
      <th>City</th>
      <th>License Type</th>
      <%= sortable_table_header :name => "Price",   :sort => "price" %>
      <%= sortable_table_header :name => "Expiration Date", :sort => "expiration_date" %>
      <th></th>
    </tr>

    <% @liquor_licenses.each do |liquor_license| %>
      <tr>
        <td><%= html_escape(liquor_license.title) %></td>
        <td><%= liquor_license.state_id ? GeoinfoState.find(liquor_license.state_id).name : '' %></td>
        <td><%= liquor_license.city_id ? GeoinfoCity.find(liquor_license.city_id).name : '' %></td>
        <td><%= liquor_license.license_type ? liquor_license.license_type.license_code + '-' + liquor_license.license_type.description : ''%></td>      <td><%= liquor_license.price != 0 ? liquor_license.price  : '' %> <%=  liquor_license.price != 0 ? '$':'' %></td>
        <td><%= liquor_license.expiration_date %></td>
        <td><%= link_to 'View', :action => "view" , :id => liquor_license.id %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @liquor_licenses %>
  <br />
  <%= submit_tag("Search") %>
<% end %>

app/views/liquor_licenses/get_for_buy.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<%= form_for :liquor_license, :html => { :method => :get} do |f| %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $("select#liquor_license_state_id").change(function(){
        $.getJSON("/liquor_licenses/get_cities",{id: $(this).val(), ajax: 'true'}, function(j){
          var options = '';
          options +='<option value=""></option>';
          for (var i = 0; i < j.length; i++) {
       
            options += '<option value="' + j[i]['geoinfo_city']['id'] + '">' + j[i]['geoinfo_city']['name'] + '</option>';
          }
          $("select#liquor_license_city_id").html(options);

        })
      })
    })
  </script>  
  <%= f.label :title %>
  <%= f.text_field :title, :value => params[:liquor_license] ? params[:liquor_license][:title] : '' %>
  <%= f.label :state %>
  <%= f.select(:state_id, GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] }, :selected  => params[:liquor_license] ? params[:liquor_license][:state_id] : '', :include_blank => true) %> 
  <%= f.label :city %>
  <%= f.select(:city_id, @cities_first ? @cities_first.collect {|c| [ c.name, c.id ]} : '', :selected => @selected_city ? @selected_city.id : '' , :include_blank => true) %> 
  <%= f.label :license_type %>
  <%= f.select(:license_type_id, LicenseType.find(:all, :order => 'license_code asc').collect {|c| [c.license_code + '-' + c.description, c.id ] },  :selected  => params[:liquor_license] ? params[:liquor_license][:license_type_id] : '', :include_blank => true) %> 
  <br/>
  <%= f.label :price %>
  <%= f.text_field :price_min ,  :value => params[:liquor_license] ? params[:liquor_license][:price_min] : ''%> 
  <%= f.text_field :price_max ,  :value => params[:liquor_license] ? params[:liquor_license][:price_max] : ''%> 

  <h1>Listing Liquor Licenses for Buyer</h1>

  <table>
    <tr>
      <%= sortable_table_header :name => "Title",  :sort => "title" %>
      <th>State</th>
      <th>City</th>
      <th>License Type</th>
      <%= sortable_table_header :name => "Price",   :sort => "price" %>

      <%= sortable_table_header :name => "Expiration Date", :sort => "expiration_date" %>
      <th></th>
    </tr>

    <% @liquor_licenses.each do |liquor_license| %>
      <tr>
        <td><%= html_escape(liquor_license.title) %></td>
        <td><%= liquor_license.state_id ? GeoinfoState.find(liquor_license.state_id).name : '' %></td>
        <td><%= liquor_license.city_id ? GeoinfoCity.find(liquor_license.city_id).name : '' %></td>
        <td><%= liquor_license.license_type ? liquor_license.license_type.license_code + '-' + liquor_license.license_type.description : ''%></td>
        <td> <%= liquor_license.price != 0 ? '$':'' %><%= liquor_license.price != 0 ? liquor_license.price  : '' %></td>
        <td><%= liquor_license.expiration_date %></td>
        <td><%= link_to 'View', :action => "view" , :id => liquor_license.id %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @liquor_licenses %>
  <br />
  <%= submit_tag("Search") %>
<% end %>

app/views/liquor_licenses/get_for_sale.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<%= form_for :liquor_license, :html => { :method => :get} do |f| %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $("select#liquor_license_state_id").change(function(){
        $.getJSON("/liquor_licenses/get_cities",{id: $(this).val(), ajax: 'true'}, function(j){
          var options = '';
          options +='<option value=""></option>';
          for (var i = 0; i < j.length; i++) {
       
            options += '<option value="' + j[i]['geoinfo_city']['id'] + '">' + j[i]['geoinfo_city']['name'] + '</option>';
          }
          $("select#liquor_license_city_id").html(options);

        })
      })
    })
  </script>
  <%= f.label :title %>
  <%= f.text_field :title, :value => params[:liquor_license] ? params[:liquor_license][:title] : '' %>
  <%= f.label :state %>
  <%= f.select(:state_id, GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] }, :selected  => params[:liquor_license] ? params[:liquor_license][:state_id] : '', :include_blank => true) %> 
  <%= f.label :city %>
  <%= f.select(:city_id, @cities_first ? @cities_first.collect {|c| [ c.name, c.id ]} : '', :selected => @selected_city ? @selected_city.id : '' , :include_blank => true) %> 
  <%= f.label :license_type %>
  <%= f.select(:license_type_id, LicenseType.find(:all, :order => 'license_code asc').collect {|c| [c.license_code + '-' + c.description, c.id ] },  :selected  => params[:liquor_license] ? params[:liquor_license][:license_type_id] : '', :include_blank => true) %> 
  <h1>Listing Liquor Licenses for Sale</h1>

  <table>
    <tr>
      <%= sortable_table_header :name => "Title",  :sort => "title" %>
      <th>State</th>
      <th>City</th>
      <th>License Type</th>
      <%= sortable_table_header :name => "Expiration Date", :sort => "expiration_date" %>

      <th></th>
    </tr>


    <% @liquor_licenses.each do |liquor_license| %>
      <tr>
        <td><%= html_escape(liquor_license.title) %></td>
        <td><%= GeoinfoState.find(liquor_license.state_id).name %></td>
        <td><%= liquor_license.city_id ? GeoinfoCity.find(liquor_license.city_id).name : '' %></td>
        <td><%= liquor_license.license_type.license_code + '-' + liquor_license.license_type.description %></td>
        <td><%= liquor_license.expiration_date %></td>
        <td><%= link_to 'View', :action => "view" , :id => liquor_license.id %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @liquor_licenses %>

  <br />
  <%= submit_tag("Search") %>
<% end %>

app/views/liquor_licenses/get_my_auction.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>My Auction</h1>

<table>
  <tr>
    <th>Title</th>
    <th>State</th>
    <th>City</th>
    <th>License Type</th>
    <th>Price</th>
    <th>Expiration Date</th>
    <th></th>
  </tr>


  <% @liquor_license_auctions.each do |liquor_license_auction| %>
    <tr>
      <td><%= LiquorLicense.find(liquor_license_auction.liquor_license_id).title %></td>
      <td><%= LiquorLicense.find(liquor_license_auction.liquor_license_id).state_id ? GeoinfoState.find(LiquorLicense.find(liquor_license_auction.liquor_license_id).state_id).name : '' %></td>
      <td><%= LiquorLicense.find(liquor_license_auction.liquor_license_id).city_id ? GeoinfoCity.find(LiquorLicense.find(liquor_license_auction.liquor_license_id).city_id).name : '' %></td>
      <td><%= LiquorLicense.find(liquor_license_auction.liquor_license_id).license_type ?  LiquorLicense.find(liquor_license_auction.liquor_license_id).license_type.license_code + '-' + LiquorLicense.find(liquor_license_auction.liquor_license_id).license_type.description : ''%></td>
      <td> $ <%= liquor_license_auction.price %> <td/>
      <td><%= LiquorLicense.find(liquor_license_auction.liquor_license_id).expiration_date %></td>
      <td>
        <% if liquor_license_auction.status == true %>
          <form action="https://www.escrow.com/ecart/StartTransaction.asp" method="post">
            <input name="pid" value="6079" type="hidden">
            <input name="item" value="liquor license" type="hidden">
            <input name="desc" value="liquor license" type="hidden">
            <input name="qty" value="1" type="hidden">
            <input name="price" value="<%= liquor_license_auction.price %>" type="hidden">
            <input name="ship" value="0" type="hidden">
            <input name="type" value="GM" type="hidden">
            <input name="submit" value="Buy It Now" type="submit">
            </form>
          <% end %>
          </td>
          </tr>
        <% end %>
        </table>
        <%= will_paginate @liquor_license_auctions %>

        <br />
        <%= submit_tag("Search") %>

app/views/liquor_licenses/index.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Listing My Liquor Licenses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>State</th>
    <th>City</th>
    <th>Price</th>
    <th>Expiration date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @liquor_licenses.each do |liquor_license| %>
    <tr>
      <td><%= html_escape(liquor_license.title) %></td>
        <td><%= GeoinfoState.find(liquor_license.state_id).name %></td>
        <td><%= liquor_license.city_id ? GeoinfoCity.find(liquor_license.city_id).name : '' %></td>
      <td><%= liquor_license.price != 0 ? liquor_license.price  : '' %> <%=  liquor_license.price != 0 ? '$':'' %></td>
      <td><%= liquor_license.expiration_date %></td>
      <td><%= link_to 'Show', liquor_license %></td>
      <td><%= link_to 'Edit', edit_liquor_license_path(liquor_license) %></td>
      <td><a href="liquor_licenses/delete_record/<%=  liquor_license.id %>" onclick="return confirm('Are you sure');" >Destroy</a> </td>
    </tr>
  <% end %>
</table>
  <%= will_paginate @liquor_licenses %>
<br />

<%= link_to 'New Liquor license', new_liquor_license_path %>

app/views/liquor_licenses/new.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>New Liquor License</h1>

<%= render 'form' %>

<%= link_to 'Back', liquor_licenses_path %>

app/views/liquor_licenses/show.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= html_escape(@liquor_license.title) %>
</p>
<p>
  <b>License Type:</b>
  <%= @liquor_license.license_type ? @liquor_license.license_type.license_code + '-' + @liquor_license.license_type.description : '' %>
</p>

<p>
  <b>State:</b>
  <%= @liquor_license.state_id ?  GeoinfoState.find(@liquor_license.state_id).name : '' %>
</p>

<p>
  <b>City:</b>
  <%= @liquor_license.city_id ? GeoinfoCity.find(@liquor_license.city_id).name : ''  %>
</p>

<p>
  <b>Price:</b>
  <%= @liquor_license.price %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @liquor_license.expiration_date %>
</p>
<table>
  <tr>
    
    <th>Email:</th>
    <th>Price</th>
   
    <th></th>
  </tr>

<% @liquor_license_auctions.each do |liquor_license_auction| %>
  <tr>
    <td><%= User.find(liquor_license_auction.bidder_id).email %></td>
    <td>$ <%= liquor_license_auction.price %></td>
    <td><a href="http://www.escrow.com/partner.asp?pid=6079" onclick="accept('<%= liquor_license_auction.id  %> ');"><img src="https://www.escrow.com/affiliate/banner-88x31.gif" width="88" height="31" alt="Escrow.com: Buy or Sell Online Without the Fear of Fraud" border="0"></a></td>
  </tr
    <script type="text/javascript" charset="utf-8">
     function accept(id) {
        $.getJSON("/liquor_licenses/accept",{id: id, ajax: 'true'}, function(j){
        })
     }

  </script>
<% end %>
</table>

<%= link_to 'Back', url_for(:back) %>