config/routes.rb
Liquorlicensehq::Application.routes.draw do
  
  resources :criterias

  resources :license_types

  resources :user_details

  resources :liquor_license_auctions

  get "home/index"
  get "users/login"
  get "users/confirm"
  get "liquor_licenses/get_my_auction"
  get "users/import_data"
  get "liquor_licenses/get_cities"
  get "liquor_licenses/delete_record"
  get "liquor_licenses/accept"
  get "users/logout"
  get "users/check_criteria"
  get "criterias/delete_record"
  get "users/private"
  get "users/contact_us"
  get "home/search"
  get "users/sendmail_criteria_activity"
  get "users/forgot"
  get "users/sendmail"
  get "liquor_licenses/paypal_request"
  get "liquor_licenses/get_craigslist"
  get "liquor_licenses/get_for_sale"
  get "liquor_licenses/get_for_buy"
  get "liquor_licenses/get_for_both"
  get "users/check_bid"
  get "users/sendmail_bid_activity"
  resources :users
  resources :liquor_licenses

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  validates :real_name, :street_address, :state_id, :post_code ,:presence => true
  validates_numericality_of :post_code, :only_integer => true, :message => "can only be integer"
  belongs_to :user
    def savelogo(fileio)
    # ENSURE WE HAVE A FILE AND IT IS THE CORRECT CONTENT TYPE
    if (fileio && fileio.content_type =~ /^image/) then

      # GET THE EXTENSION, DIRECTORY, AND VIRTUAL PATH
      extension = File.extname(fileio.original_filename)
      dir = Rails.root.join('public','uploads')
      path = File.join('uploads')

      # CREATE THE DIRECTORY IF IT DOESNT EXIST
      Dir.mkdir(dir) unless File.exist?(dir)

      # WRITE THE ORIGINAL FILE FOR USE IN MINIMAGICK
      file_name = self.id.to_s + '_' + Time.now.to_i.to_s
      File.open(dir + (file_name + extension), "wb") do |f|
        f.write(fileio.read)
      end

      # PERFORM THE MINIMAGICK CHANGES
      mm = MiniMagick::Image.from_file(dir + (file_name + extension))
      mm.resize("60X60")
      mm.write( "public/uploads/" + (file_name + extension))

      # UPDATE ATTRIBUTES
      self.avatar = "/"+ path + "/" + file_name + extension
      self.save()
    end
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  # GET /user_details
  # GET /user_details.xml
  def index
    @user_details = UserDetail.all
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.username != 'admin'
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_details }
    end
  end

  # GET /user_details/1
  # GET /user_details/1.xml
  def show
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_detail }
    end
  end

  # GET /user_details/new
  # GET /user_details/new.xml
  def new
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user == nil
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
    @user_detail = UserDetail.new
    @cities_first = GeoinfoCity.where(:state_id => '2').find :all, :order => "name asc"
    @selected_city = nil
    logger.info @cities_first
    if @user_detail.city_id
      @selected_city = GeoinfoCity.find(@user_detail.city_id)

    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_detail }
    end
  end

  # GET /user_details/1/edit
  def edit
    @user_detail = UserDetail.find(params[:id])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    if session[:user_id] != nil and session[:user_id] != ''
      @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])

      if @valid_user.id != @user_detail.user_id
        flash[:error] = "You don't have access to this section." 
        redirect_to '/'
        return
      end 
      
    else
      flash[:error] = "You don't have access to this section." 
      redirect_to '/'
      return
    end
   
    @state_first = GeoinfoState.find(@user_detail.state_id)
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '0').find :all, :order => "name asc"
    @selected_city = nil
    if @user_detail.city_id
      @selected_city = GeoinfoCity.find(@user_detail.city_id)

    end

  end

  # POST /user_details
  # POST /user_details.xml
  def create
    @user_detail = UserDetail.new(params[:user_detail])
    @valid_user = User.find(:first, :conditions => ["username = ? ", session[:user_id]])
    @user_detail.user_id = @valid_user.id
    @valid_user.user_detail = @user_detail
    @valid_user.save
    @state_first = GeoinfoState.find(:first, :order => 'name asc')
    if params[:user_detail][:state_id]
      @state_first = GeoinfoState.find(params[:user_detail][:state_id])
    end
    @cities_first = GeoinfoCity.where(:state_id => @state_first ? @state_first.id : '0').find :all, :order => "name asc"
    @selected_city = nil
    if params[:user_detail][:city_id] 
      @selected_city = GeoinfoCity.where(:id => params[:user_detail][:city_id]).first

    end
    respond_to do |format|
      if @user_detail.save
        if params[:logo] then
          @user_detail.savelogo(params[:logo])
        end
        format.html { redirect_to(@user_detail, :notice => 'User detail was successfully created.') }
        format.xml  { render :xml => @user_detail, :status => :created, :location => @user_detail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_details/1
  # PUT /user_details/1.xml
  def update
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      if @user_detail.update_attributes(params[:user_detail])
        if params[:logo] then
          @user_detail.savelogo(params[:logo])
        end
        format.html { redirect_to(@user_detail, :notice => 'User detail was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.xml
  def destroy
    @user_detail = UserDetail.find(params[:id])
    @user_detail.destroy

    respond_to do |format|
      format.html { redirect_to(user_details_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_form.html.erb
<%= form_for(@user_detail, :html => { :multipart => true}) do |f| %>
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>

      <ul>
      <% @user_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :real_name %><br />
    <%= f.text_field :real_name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
<script type="text/javascript" charset="utf-8">
$(function(){
  $("select#user_detail_state_id").change(function(){
    $.getJSON("/liquor_licenses/get_cities",{id: $(this).val(), ajax: 'true'}, function(j){
            var options = '';
      for (var i = 0; i < j.length; i++) {
     
        options += '<option value="' + j[i]['geoinfo_city']['id'] + '">' + j[i]['geoinfo_city']['name'] + '</option>';
      }
      $("select#user_detail_city_id").html(options);

    })
  })
})
</script>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.select(:state_id, GeoinfoState.find(:all, :order => 'name asc').collect {|c| [ c.name, c.id ] }) %> 
  </div>
  <div class="field">
    <%= f.label :city %><br />
   <%= f.select(:city_id, @cities_first ? @cities_first.collect {|c| [ c.name, c.id ]} : '', :selected => @selected_city ? @selected_city.id : '' ) %> 
  </div>
  <div class="field">
    <%= f.label :post_code %><br />
    <%= f.text_field :post_code %>
  </div>
<p>
  <%= image_tag @user_detail.avatar ? @user_detail.avatar : 'logo.jpg', :size => "60x60" %>
</p>
  <p>
    Logo<br />
    <%= file_field_tag 'logo' %>
  </p>
   <div class="field">
      <%= f.label :gender %><br />
      <%= f.radio_button "gender", "Male" %>Male
      <%= f.radio_button "gender", "Female" %>Female
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Editing User Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_detail %> |
<%= link_to 'Back', user_details_path %>

app/views/user_details/index.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>Listing user_details</h1>

<table>
  <tr>
    <th>Real name</th>
    <th>Street address</th>
    <th>City</th>
    <th>State</th>
    <th>Post code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_details.each do |user_detail| %>
  <tr>
    <td><%= html_escape(user_detail.real_name) %></td>
    <td><%= html_escape(user_detail.street_address) %></td>
    <td><%= user_detail.city %></td>
    <td><%= user_detail.state %></td>
    <td><%= user_detail.post_code %></td>
    <td><%= link_to 'Show', user_detail %></td>
    <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
    <td><%= link_to 'Destroy', user_detail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User detail', new_user_detail_path %>

app/views/user_details/new.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<h1>New User Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', user_details_path %>

app/views/user_details/show.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<p id="notice"><%= notice %></p>
<p>
  <b>Avatar:</b>
   <%= image_tag @user_detail.avatar ? @user_detail.avatar : 'logo.jpg', :size => "60x60" %>
</p>
<p>
  <b>Real name:</b>
  <%= html_escape(@user_detail.real_name) %>
</p>

<p>
  <b>Street address:</b>
  <%= html_escape(@user_detail.street_address) %>
</p>

<p>
  <b>State:</b>
  <%= GeoinfoState.find(@user_detail.state_id).name %>
</p>

<p>
  <b>City:</b>
  <%= @user_detail.city_id ? GeoinfoCity.find(@user_detail.city_id).name : ''  %>
</p>

<p>
  <b>Post code:</b>
  <%= @user_detail.post_code %>
</p>
<p>
 <b>Gender:</b>
  <%= @user_detail.gender %>
</p>


<%= link_to 'Edit', edit_user_detail_path(@user_detail) %> |
<%= link_to 'Back', user_details_path %>